version: '2.1'

jobs:
  build-and-deploy:
    machine:
      image: ubuntu-2204:2023.07.1
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Setup Python 3.10
          command: |
            sudo apt-get update
            sudo apt-get install -y python3.10
            python3.10 --version
      - run:
          name: Setup AWS SAM CLI
          command: |
            sudo apt-get update
            pip3 install awscli
            aws --version
            pip3 install aws-sam-cli
            sam --version
      - run:
          name: Build Image
          command: |
            echo "Build Lambda Functions image..."
            sam build \
              --use-container \
              --parallel \
              --no-cached \
              --region ${AWS_REGION}
      - run:
          name: Deploy Lambda Functions
          command: |
            echo "Deploy Lambda Functions..."
            sam deploy \
              --no-fail-on-empty-changeset \
              --region ${AWS_REGION} \
              --stack-name dbt-project-visualizer \
              --resolve-s3 \
              --capabilities CAPABILITY_IAM \
              --no-confirm-changeset \
              --image-repository ${ECR_REPOSITORY} \
              --parameter-overrides \
                SentryDSN=${SENTRY_DSN}

workflows:
  version: 2
  dbt_analyzer_lambda_pipeline:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              ignore: /.*/  # Ignore all branch builds
            tags:
              only: /^v.*/  # Only trigger for tags with a pattern like v1.0, v2.5.3, etc.
